### ISSUE TITLE
A central place (JSON file?) to provide comprehensive Field Mapping Guidelines for User-friendly understanding of the implied rule.

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#47]
> Other fields are supported and can be used during an analysis. As a basic recommmendation, you should include a field for sample type (e.g., "Type") with strings for each type of sample (i.e., standards are marked 'STD', blanks are 'BLANK', etc.) and a "Batch" field if your samples were collected in multiple batches and you want to do batch correction. All fields are read in and stored in the underlying data structures and any number of fields are supported.

> Here a dictionary is used that contains various fields that need to be standardized under the heading "mappings". For each such field there can be multiple values, each a key in a sub directionary containing multiple key: value pairs indicating what substrings when observed in any of the specified csv fields should result in that field being populated with the specified value.

> For example,

```
 "sample_type":
        {
        "qstd": {
            "substrings": ["qstd", "QSTD", "Qstd"],
            "search": ["File Name", "Sample ID"]
            },
        ...
```

Trying to understand all the type mapping but could not easily find the solutions. Better to point to a place where exhausted mapping information are provided.

Best,
MG

**Comment by jmmitc06** [comment]
I'm not sure what you are asking for exactly. I cannot provide comprehensive mapping information since the nature of the mappings that you depends on your data. I can clarify the documentation but the main point is that you have a top level field, here is "sample_type" that you want to populate with the value "qstd" if any of the substrings are present in any of the search fields. The preprocessing step is totally unneeded for the analysis. You can simply provide a manually curated sequence / sample metadata sheet.

**Comment by jmmitc06** [comment]
The documentation has been updated. Hopefully it is more clear now.

**Comment by gmhhope** [comment]
Thanks! Much better after the workflow was there!
