### ISSUE TITLE
ThermoRawFileConverter does not work on GC Data

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#75]
We need a standalone wrapper around MSConvert for the GC data conversion. If we had a docker container that has msconvert inside and the appropriate entry point, we can convert all the data in the pipeline easily. Yuanye, does this seem feasible? Its probably the same on Sumner just using singularity.

**Comment by YuanyeChi** [comment]
Hi Josh,
I just tried to run the official MSconvert docker container on our M2 chip, and it failed as expected since Wine is not supported on Mchip. Because MSConvert also uses vendor's convert software, I just go back to ThermoRawFileParser to have another try. After one time crash, it worked! I don't know the reason of crash because I tried several time later and I cannot reproduce the error anymore. 
The command I use is just `mono ./ThermoRawFileParser1.4.2/ThermoRawFileParser.exe -d GC-Orbi` and `mono ./ThermoRawFileParser1.4.2/ThermoRawFileParser.exe -i GC-Orbi/RTstd_1.raw`. Please let me know if you can also use ThermoRawFileParser on GC Orbi data.
<img width="527" alt="image" src="https://github.com/user-attachments/assets/0719d60e-25c6-4156-be36-3f2067293380">

**Comment by jmmitc06** [comment]
I figured it out. The version of the converter that is being downloaded from the goolgestoreapi is the version 1.1.8 version, not the more recent one. That version seems to have a problem. 

We should move away from hosting this ourselves anyways. I'm going to have it download the most recent release from their github.

**Comment by YuanyeChi** [comment]
Here is the dockerized msconvert: https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses. I will spend time making it work on M chip mac.
